spring.application.name=RestaurantService

server.port=8081
# Eureka server location (camelCase serviceUrl and trailing slash)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
